In [13]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.losses import CategoricalCrossentropy
from System import FICAR

# System

In [6]:
system = FICAR(n_classes=4, class_names=['male_w', 'female_w', 'male_b', 'female_b'])
system.train("dummyDL")

P(0,1)-> Fit with pair ('male_w', 'female_w')
P(0,2)-> Fit with pair ('male_w', 'male_b')
P(0,3)-> Fit with pair ('male_w', 'female_b')
P(1,2)-> Fit with pair ('female_w', 'male_b')
P(1,3)-> Fit with pair ('female_w', 'female_b')
P(2,3)-> Fit with pair ('male_b', 'female_b')


In [7]:
y_pred = system.predict('dummyIns')
print(system.decisions)
print(y_pred)

[[0.         0.3120504  0.95452845 0.81355755]
 [0.6879496  0.         0.24934205 0.20867684]
 [0.04547155 0.75065795 0.         0.10901914]
 [0.18644245 0.79132316 0.89098086 0.        ]]
male_b


# Fuzzy Loss Function

In [28]:
from FuzzyLoss import FuzzyLoss

y_true = tf.constant(tf.keras.utils.to_categorical([4, 1]))
y_pred = tf.constant([[0 , .7 , 0 ,0 ,  .3], [0 , .6 , .3 ,0 ,  .1]])

In [29]:
print('TF-CELoss : ', CategoricalCrossentropy()(y_true, y_pred).numpy())
print('FuzzyLoss : ', FuzzyLoss(gamma=0.5)(y_true, y_pred).numpy())

TF-CELoss :  0.8573992
FuzzyLoss :  0.66519517
