In [1]:
import numpy as np

from ficar import FICAR

In [6]:
system = FICAR(n_classes=4, class_names=['male_w', 'female_w', 'male_b', 'female_b'])
system.train()

In [7]:
instance = 'ins'
y_pred = system.predict(instance)
print(system.decisions)
print(y_pred)

ARGMAX IN (1,2)
[[0.         0.09669265 0.69732342 0.69299275]
 [0.90330735 0.         0.9864615  0.19342668]
 [0.30267658 0.0135385  0.         0.72727808]
 [0.30700725 0.80657332 0.27272192 0.        ]]
male_b
